version: '3.7'
services:
  postgres:
    image: postgres
    container_name: postgress
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DATABASE: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
